apiVersion: v1
kind: ServiceAccount
metadata:
  name: udf-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: udf-sa
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: udf-sa
subjects:
  - kind: ServiceAccount
    name: udf-sa
    namespace: kube-system