controller:
  appprotect: 
    enable: true
  appprotectdos:
    enable: true
  enableSnippets: true
  image:
    repository: ghcr.io/aknot242/nginx-plus-ingress
    tag: 2.2.2-SNAPSHOT-a88b7fe
  nginxPlus: true
  nginxStatus:
    allowCidrs: 9000
    port: 9000
  serviceAccount:
    imagePullSecretName: ghcr
prometheus:
  create: true