apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-plus-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifests/nginx-ingress-subchart.yml
    repoURL: https://github.com/codygreen/modern_app_jumpstart_workshop.git
    targetRevision: day3-setup
  destination:
    namespace: nginx-ingress
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true