---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-vip
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - kube-vip-cluster
            topologyKey: "kubernetes.io/hostname"
      containers:
      - args:
        - manager
        env:
          - name: vip_interface
            value: "ens5"
          - name: vip_configmap
            value: "kubevip" 
          - name: vip_arp
            value: "true"
          - name: vip_loglevel
            value: "5"
        image: ghcr.io/kube-vip/kube-vip:latest
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
